version: '3.4'
services:
    proxxy:
        container_name: proxxy
        image: proxxy # name image for datadog tracing
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        env_file:
            - .env
        ports:
            - ${PROXXY_PORT}:${PROXXY_PORT}
        volumes:
            - ./:/go/cmd/app
